#pragma config(Sensor, dgtl1,  limitSwitch,    sensorTouch)
#pragma config(Sensor, dgtl2,  bumpSwitch,     sensorTouch)
#pragma config(Sensor, dgtl5,  ultrasonic,     sensorSONAR_inch)
#pragma config(Sensor, dgtl12, LEDOne,         sensorLEDtoVCC)
#pragma config(Motor,  port2,           starboardMotor, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           portMotor,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           servo,         tmotorServoStandard, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "portOperation.c"
#include "starboardOperation.c"

/*
	Group: Joe, %NAME%, %NAME%, %NAME%
	Class: Computer Engineering, block C
	Teacher: Mrs. Marcou
	GitHub: https://github.com/KenwoodFox/CE-Playground

	psudo:
	task: port wheel turns cw at 127/2 while the bump switch is pressed
	task: turn the starboard motor CW, then CCW alternativly for 1 rev each at low speed, while the limit switch is pressed
	task: ultrasonic sensor tpo turn off a lit LED when an object is closer than 4 inches, the first instance of this will start the servo motor running

	notes:
		Looks good to me doc
*/

int error = 0;

task main()
{
	startTask(portOperation);
	startTask(starboardOperation);
	while(error < 1)
	{
		if(SensorValue(ultrasonic) > 4)
		{
			turnLEDOn(LEDOne);
			stopMotor(servo);
		}
		else
		{
			turnLEDOff(LEDOne);
			startMotor(servo, 90);
		}
		delay(30);
	}
}
