#pragma config(Sensor, dgtl1,  limitSwitch,    sensorTouch)
#pragma config(Sensor, dgtl2,  bumpSwitch,     sensorTouch)
#pragma config(Sensor, dgtl12, LEDOne,         sensorLEDtoVCC)
#pragma config(Motor,  port2,           starboardMotor, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           portMotor,     tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "portOperation.c"
#include "starboardOperation.c"

/*
	Group: Joe, %NAME%, %NAME%, %NAME%
	Class: Computer Engineering, block C
	Teacher: Mrs. Marcou
	GitHub: https://github.com/KenwoodFox/CE-Playground

	stpid code that coding teacher make you do cuz they dont trust you to just not be stupid and forget what you're making Code:
	task: port wheel turns cw at 127/2 while the bump switch is pressed
	task: turn the starboard motor CW, then CCW alternativly for 1 rev each at low speed, while the limit switch is pressed
	task: ultrasonic sensor tpo turn off a lit LED when an object is closer than 4 inches, the first instance of this will start the servo motor running... (missing information)

	notes:
		Looks good to me doc
*/

int error = 0;

task main()
{
	startTask(portOperation);
	startTask(starboardOperation);
	while(error < 1)
	{
		delay(2000);
	}
}
