#pragma config(Sensor, dgtl1,  LED,            sensorLEDtoVCC)
#pragma config(Sensor, dgtl10, bowSwitch,      sensorTouch)
#pragma config(Sensor, dgtl11, sternSwitch,    sensorTouch)
#pragma config(Sensor, dgtl12, bumpSwitch,     sensorTouch)
#pragma config(Motor,  port1,           starboardAft,  tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port8,           starboardFore, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           portAft,       tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port10,          portFore,      tmotorServoContinuousRotation, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "drivetrain.h" //include the drivetrain header
#include "init.h" //Include init.h, init.h also includes void startup();
#include "tankSpin.h"
#include "blink.h"

void seekCenter()
{
	int scanTime = 15;
	int seekLocation = 0;

	blink(2, LED);
	while(SensorValue[sternSwitch] != 1) //For as long as the stern is not depressed
	{
		standard(-40); //go backwards at -40
		delay(scanTime); //scan every
	}

	blink(3, LED);
	while(SensorValue[bowSwitch] != 1) //for as long as the bow is not depressed
	{
		standard(60);
		delay(scanTime);
		seekLocation++; //add a location seek number
	}

	seekLocation = seekLocation * scanTime; //returns the seekLocation in ms
	standard(-60);
	delay(seekLocation); //go in reverse for half the duration going forwards
	halt();
}


task main()
{
	//while(true) //forever
	//{
		startup(bumpSwitch, LED);
		seekCenter(); //find the center of the table
		tankSpin(-90); //turn to face the other wall
	//}
}
