#pragma config(Sensor, dgtl1,  LED,            sensorLEDtoVCC)
#pragma config(Sensor, dgtl10, bowSwitch,      sensorTouch)
#pragma config(Sensor, dgtl11, sternSwitch,    sensorTouch)
#pragma config(Sensor, dgtl12, bumpSwitch,     sensorTouch)
#pragma config(Motor,  port1,           starboardAft,  tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port8,           starboardFore, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           portAft,       tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port10,          portFore,      tmotorServoContinuousRotation, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "drivetrain.h" //include the drivetrain header
#include "init.h" //Include init.h, init.h also includes void startup();
#include "tankSpin.h"
#include "blink.h"

void debug()
{
	standard(-40);
}

void seekCenter()
{
	int scanTime = 15;
	int seekLocation = 0;

	while(SensorValue[sternSwitch] == 0) //For as long as the stern is not depressed
	{ //go in reverse to find the wall
		standard(30); //go backwards at -40
		delay(scanTime); //scan every
		standard(-30);
		delay(250);
	}

	//blink(3, LED);
	while(SensorValue[bowSwitch] == 0) //for as long as the bow is not depressed
	{
		standard(50);
		delay(scanTime);
		seekLocation++; //add a location seek number
	}

	seekLocation = seekLocation * scanTime; //returns the seekLocation in ms
	standard(-50);
	delay(seekLocation / 2 - 150); //go in reverse for half the duration going forwards
	halt();
}

void spiral() //This function will drive the robot in a slowly growing spiral, teroeticly from the center of its traverse
{
	//for as long as neither bumpswitch is pressed, run the motors adding every time delay, a speed to the motors, that rsult in a slowly growing circle
	while(SensorValue[bowSwitch] != 1 && SensorValue[sternSwitch] != 1)
	{

	}
}


task main()
{
	while(true) //forever
	{
		//debug();

		startup(bumpSwitch, LED);
		seekCenter(); //find the center of the table
		tankSpin(-90); //turn to face the other wall
	}
}
