#pragma config(Sensor, dgtl1,  LED,            sensorLEDtoVCC)
#pragma config(Sensor, dgtl12, bumpSwitch,     sensorTouch)
#pragma config(Motor,  port1,           starboardAft,  tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port5,           portAft,       tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port6,           starboardFore, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port10,          portFore,      tmotorServoContinuousRotation, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//This function by Joe

void starboardDriveTrain(float speed) //function to drive each of the starboard wheels using value speed,
{
	int tune = 1.0000; //tune adjust for the variablity of the wheels

	startMotor(starboardFore, (speed * tune)); //Set both motors to the speed given and multiply them by thr tune value
	startMotor(starboardAft, (speed * tune));
}

void portDriveTrain(float speed) //function to drive each of the port wheels using value speed,
{
	int tune = 1.0000; //tune adjust for the variablity of the wheels

	startMotor(portFore, (speed * tune)); //Set both motors to the speed given and multiply them by thr tune value
	startMotor(portAft, (speed * tune));
}

//this function by joe, remeber to include my drivetrain.c before including this file

void easyGas(int targetSpeed, int accelValue, float accelDirection)
{
	float speed = 0; //arb value for the current speed

	while(speed != targetSpeed && speed < 127 && speed > -127) //while you are not at target speed OR the speed value is bigger than the max output, THIS WILL TRIGGER IN CASE OF AN ERROR
	{
		speed = speed + accelDirection; //add accelDirection to the speed value
		delay(accelValue); //delay for this long
		starboardDriveTrain(speed); //set the speed
		portDriveTrain(speed);
	}
}

task main()
{
	while(SensorValue[bumpSwitch] != true) //while bumpswitch is not pressed
	{
		delay(10); //wait 10ms
	}

	delay(900); //after pressing the bump switch, wait 900ms before starting the program

	easyGas(100, 5, 1); //accelerate at a rate of 0.5 every 5ms to 100 pwm
	delay(4000); //magic delay for the leangth of the
	easyGas(0, 5, -1);	//accelerate at a rate of -0.5 every 5ms to 100 pwm
}
