#pragma config(Motor,  port1,           starboardFore, tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port5,           portFore,      tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port6,           portAft,       tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port10,          starboardAft,  tmotorVex393_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	startMotor(starboardFore, 100 * 1);
	startMotor(portFore, 100 * 1);
	delay(400);
	stopMotor(starboardFore);
	stopMotor(portFore);
}
