#pragma config(Sensor, dgtl1,  limitSwitch,    sensorTouch)
#pragma config(Sensor, dgtl2,  bumpSwitch,     sensorTouch)
#pragma config(Sensor, dgtl12, LEDOne,         sensorLEDtoVCC)
#pragma config(Motor,  port2,           starboardMotor, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           portMotor,     tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "flash.c"
#include "motorInit.c"

task driveTask() //Tasks need to be defined before the task main, as they will compile in order
{
	int trip = false;

	startMotor(starboardMotor, -80);
	startMotor(portMotor, -80);

	while(trip == false)
	{
		if(SensorValue(limitSwitch) == 1)
		{
			trip = true;
			delay(20);
		}
		else
		{
			delay(20);
		}
	}
}

task main()
{
	//things to run once:
	motorInit();

	//things to run over and over
	while(true){
		startTask(blink, 5);
		startTask(driveTask, 10);

		delay(2000);
	}
}
