#pragma config(Sensor, dgtl1,  limitSwitch,    sensorTouch)
#pragma config(Sensor, dgtl2,  bumpSwitch,     sensorTouch)
#pragma config(Sensor, dgtl12, LEDOne,         sensorLEDtoVCC)
#pragma config(Motor,  port2,           starboardMotor, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           portMotor,     tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "toggleBlink.h" //Blink on/off command
#include "runMotors.h" //motor drive command
#include "blink.h" //include the blink subroutine

int operation = true;
//int blinkState = false;

task main() //This task called upon robot start
{
	startTask(runMotors); //Start the motors Subroutine
	startTask(blink); //Start the blink subroutine

	while(operation == true) //While there are no critical opperations
	{
		toggleBlink(); //run the blink routine
		delay(10);
	}
}
