#pragma config(UART_Usage, UART1, uartUserControl, baudRate115200, IOPins, None, None)
#pragma config(Sensor, dgtl1,  LED,            sensorLEDtoVCC)
#pragma config(Sensor, dgtl11, sternSwitch,    sensorTouch)
#pragma config(Sensor, dgtl12, bumpSwitch,     sensorTouch)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "../../libraries/blink.h" //Include the blink header
#include "../../libraries/init.h" //include the init header

void handshake(char statusLight, char UART) //This handshake function will wait untill the arm sends us the lowercase letter 'r' this will be the sign that it is ready to go
{
	char nextChar = getChar(UART); //take the waiting char in
	//handshake void allows us to wait untill the robot arm says its ready
	while(nextChar != 'r') //for as long as the next char is not r
	{
		blink(1,LED);
		nextChar = getChar(UART);
	}
}

task main()
{
	handshake(LED, UART1);
}
