#pragma config(Sensor, dgtl1,  maxUp,          sensorTouch)
#pragma config(Sensor, dgtl2,  maxDown,		   sensorTouch)
#pragma config(Motor,  port1,           fire,          tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           servo,         tmotorServoStandard, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "eStop.h"
#include "zero.h"

/* 
 * Etot code piz' dets
 */

boolean error = false; //Error is the global 'break' command, its like an E stop, we can imput a series of error event triggers anywhere we choose

//Ball settings
int ball1 = 400; //Set the size of the largest ball
int ball2 = 400; //Set the size of the second largest ball
int ball3 = 400; //Set the size of the third largest ball

task main() //Main task
{
	//startTask(eStop); //Start the eStop task
	
	while(error == false) //For as long as error is true lol
	{
		setZero(); //Come to zero
		
		//Next step is to determine the ball size
		while(sensorTouch == 0 && error = false) //untill you reach sensorTouch, you must reach sensor touch within a time cap
		{
			int lockout = lockout + 1; //increase lockout by one
			
			if(lockout > 5000)
			{
				error = true;
				break();
			}
			
			delay(10);
			motor[servo] = 60; //Roll down till you hit it blayt
		}
	}
}
