#pragma config(Sensor, dgtl1,  maxUp,          sensorTouch)
#pragma config(Sensor, dgtl2,  maxDown,        sensorTouch)
#pragma config(Motor,  port2,           servo,         tmotorServoStandard, openLoop)
#pragma config(Motor,  port3,           fire,          tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//#include "eStop.h"
#include "zero.h"
#include "../../libraries/init.h" //Include init.h, init.h also includes void startup();
#include "../../libraries/lockNload.h" //Include the lockNload header

/*
* Etot code piz' dets
*/

//bool error = false; //Error is the global 'break' command, its like an E stop, we can imput a series of error event triggers anywhere we choose

//Ball settings
int ball1 = 1250; //Set the size of the largest ball
int ball2 = 3000; //Set the size of the second largest ball
int ball3 = 8500; //Set the size of the third largest ball

task main() //Main task
{
	while(true)
	{
		zero(maxUp, servo); //Come to zero
		//startup();
		lockNload(servo, maxUp, fire, ball1);
	}
}
