#pragma config(Sensor, dgtl1,  LED,            sensorLEDtoVCC)
#pragma config(Sensor, dgtl12, bumpSwitch,     sensorTouch)
#pragma config(Motor,  port1,           starboardAft,  tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port5,           portAft,       tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port6,           starboardFore, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port10,          portFore,      tmotorServoContinuousRotation, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "drivetrain.h" //include the drivetrain header
#include "easyGas.h" //include the easygas header

int i = 0;

task main()
{
	while(SensorValue[bumpSwitch] != true) //while bumpswitch is not pressed
	{
		delay(50); //wait 50ms
		turnLEDOn(LED);
		delay(50);
		turnLEDOff(LED);
	}

	while( i < 6)
	{
		delay(100);
		turnLEDOn(LED);
		delay(100);
		turnLEDOff(LED);
		i++;
	}

	easyGas(0, 100, 5, 1); //Accelerate from 0, to 100, in time increments of 5ms, forward.
	delay(4000); //magic delay for the leangth of the
	easyGas(100, 0, 5, -1);	//Accelerate from 100, to 0, in time increments of 5ms, backward.
}
