#pragma config(Sensor, in1,    linefollower,   sensorLineFollower)
#pragma config(Sensor, in2,    potentiometer,  sensorPotentiometer)
#pragma config(Sensor, in3,    lightsensor,    sensorReflection)
#pragma config(Sensor, dgtl1,  limitswitch,    sensorTouch)
#pragma config(Sensor, dgtl2,  bumpswitch,     sensorTouch)
#pragma config(Sensor, dgtl3,  encoder,        sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  ultrasonic,     sensorSONAR_inch)
#pragma config(Sensor, dgtl12, greenLED,       sensorLEDtoVCC)
#pragma config(Motor,  port1,           flashlight,    tmotorVexFlashlight, openLoop, reversed)
#pragma config(Motor,  port2,           rightmotor,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           leftmotor,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           servomotor,    tmotorServoStandard, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*

Project Title: lesson 1.2.2 2nd Mini Challenge
Team Members: Chemai
Date: //18
Section: Block C


Task Description:
1.2.2 Test bed Input/Output


Pseudocode:
when bump switch is pressed light go on and off for one second
wheel turn clockwise 1 revolution wait 2 second than reverse until limit switch is pushed
stop led when bump switch is pressed
when the limitswitch is touched
startMotors turn CW 1 revoltion wait 2 second turn back



*/


task main()
{
	while(true)
	{
		if(SensorValue(bumpswitch) == 1)
		{
			startMotor(leftmotor, 63);
			turnLEDOn(greenLED);
			wait(1);
			turnLEDOff(greenLED);
			wait(1);

		}

		else
		{
			turnLEDOff(greenLED);
			stopMotor(leftmotor);
		}

		// unknown revolution
		// make code to turn leftmotor and rightmotor CW
		// make code to turn Counter CW



		if(SensorValue(limitswitch) == 1)
		{
			startMotor(rightmotor, 30);
			wait(2);
			stopMotor(rightmotor);
			wait(2);
			startMotor(rightmotor, -30);
			wait(2);
			stopMotor(rightmotor);
			wait(2);
		}

		untilSonarLessThan(4, ultrasonic);
		turnLEDOff(greenLED);

	}
}
