#pragma config(Sensor, dgtl12, limitswitch,    sensorTouch)
#pragma config(Motor,  port1,           Backright,     tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port5,           Backleft,      tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           Frontright,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          Frontleft,     tmotorVex393_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "turn.h"

int x = 1;
string y = 2.2;

/*

Project Title: lesson 1.2.2
Team Members: Chemai
Date: //18
Section: Block C


Task Description:



Pseudocode:

turn motors on low
wait 2sec go faster
wait 2sec get faster
stopAllMotors


*/


task main()
{
	while(true) //forever
	{
		if(SensorValue(limitswitch) == 1)
		{
			wait(2);
			startMotor(Backleft, 44);
			startMotor(Backright, 44);
			startMotor(Frontleft, 44);
			startMotor(Frontright, 44);
			wait(4);
		}
		stopMotor(Backleft);
		stopMotor(Backright);
		stopMotor(Frontleft);
		stopMotor(Frontright);

		turnright(x, y);

	}
}
