#pragma config(Sensor, in1,    linefollower,   sensorLineFollower)
#pragma config(Sensor, in2,    potentiometer,  sensorPotentiometer)
#pragma config(Sensor, in3,    lightsensor,    sensorReflection)
#pragma config(Sensor, dgtl1,  limitswitch,    sensorTouch)
#pragma config(Sensor, dgtl2,  bumpswitch,     sensorTouch)
#pragma config(Sensor, dgtl3,  encoder,        sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  ultrasonic,     sensorSONAR_inch)
#pragma config(Sensor, dgtl12, greenled,       sensorLEDtoVCC)
#pragma config(Motor,  port1,           flashlight,    tmotorVexFlashlight, openLoop, reversed)
#pragma config(Motor,  port2,           rightmoter,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           leftmoter,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           servomotor,    tmotorServoStandard, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*

 Project Title: lesson 1.2.2
 Team Members: Chemai
 Date: //18
 Section: Block C


 Task Description:
 				1.2.2 Test bed Input/Output


 	Pseudocode:


*/


task main()
{




}
